[上一页：异常的概念](/ThinkingInJava原版/异常捕获/异常的概念.md)
- [基本异常](#基本异常)
      - [当你抛出一个异常的时候发生了什么？](#当你抛出一个异常的时候发生了什么)
      - [例子](#例子)

# 基本异常
当出现异常情况的时候，会阻止接下来的代码执行。但是当阻止的时候，你很可能没有足够多的上下文。你也不知道怎么处理。所以这时候你会抛出去。
例如，除法。除以0.如果做这么一个方法，进行一个参数检查是十分值得的。但是，如果发生了错误的话，你用什么方式表示参数是0，导致的异常吗？很多情况下，你可能是知道这个情况的，或许你也可以在这个场景下进行一个特殊的处理。但是如果换做别的参数呢？一个意想不到的参数？你需要做的是跳出当前的环境，向一个更高级别的环境汇报出来。
#### 当你抛出一个异常的时候发生了什么？
- 就像创建普通对象那样用new关键字在堆里创建一个对象。
- 当前程序执行停止并且在当前这个“环境”下，弹出刚刚生成的那个对象的引用
- 与此同时，异常处理机制开始接手并且寻找合适的位置继续执行逻辑。这个合适的位置就是**异常处理器**他的职责是从问题代码块恢复过来并且尝试从其他的栈开始继续执行！

#### 例子
```
if (t == null) {
    throw new NullPointerException();
}
```
上述方法抛出了一个违例。在抛出的时候就不用考虑怎么处理了，反正之后总会有一个地方处理他们！
[下一页:1.1异常的参数](/ThinkingInJava原版/异常捕获/1.1异常的参数.md)